---
extends:
  - airbnb-base
  - plugin:prettier/recommended
  - prettier/standard
env:
  node: true
  jest: true
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - './config/test.setup.js'
